### ISSUE TITLE
文件传输403，可能需要指定文件传输的存储目录

### ISSUE THREAD

**Issue by momomobinx** [xireiki/tailscale4magisk#1]
![image](https://github.com/xireiki/tailscale4magisk/assets/21970770/89a3ccca-91fb-4f60-ad05-2faac0ffed64)

**Comment by momomobinx** [comment]
看来需要改下源码里面的目录位置，软连接建不了

**Comment by xireiki** [comment]
这和本项目无关，请自行排查原因
